export const COUNTRIES = [
  { code: "", name: "Velg land", flag: "🌐" },
  { code: "DZ", name: "Algerie", flag: "🇩🇿" },
  { code: "BR", name: "Brasil", flag: "🇧🇷" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "DK", name: "Danmark", flag: "🇩🇰" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "FR", name: "Frankrike", flag: "🇫🇷" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "IT", name: "Italia", flag: "🇮🇹" },
  { code: "MA", name: "Marokko", flag: "🇲🇦" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "NO", name: "Norge", flag: "🇳🇴" },
  { code: "RU", name: "Russland", flag: "🇷🇺" },
  { code: "SA", name: "Saudi-Arabia", flag: "🇸🇦" },
  { code: "ES", name: "Spania", flag: "🇪🇸" },
  { code: "GB", name: "Storbritannia", flag: "🇬🇧" },
  { code: "SE", name: "Sverige", flag: "🇸🇪" },
  { code: "ZA", name: "Sør-Afrika", flag: "🇿🇦" },
  { code: "TR", name: "Tyrkia", flag: "🇹🇷" },
  { code: "DE", name: "Tyskland", flag: "🇩🇪" },
  { code: "US", name: "USA", flag: "🇺🇸" },
];
